### ISSUE TITLE
Image filesizes too big

### ISSUE THREAD

**Issue by Miniland1333** [kreut/libretext#4]
For your images, especially https://github.com/kreut/libretext/blob/staging/public/assets/img/soundtrap-ddwbTn5HDdQ-unsplash.jpg, the filesizes are big enough that it is affecting your site load times. Would you be able to compress these images down so that they load much faster. They should be <1MB each.

If you aren't familiar with doing this manually, you can also install [Imgbot ](https://github.com/marketplace/imgbot) onto Github to have it done automatically.

**Comment by Miniland1333** [comment]
@kreut, did you see this issue? Hopefully it won't take more than a few minutes to compress those images.

**Comment by kreut** [comment]
It didn't seem to find the offending image.

**Comment by Miniland1333** [comment]
I’m debugging, but I think it is just because it doesn’t handle jpg by default.

**Comment by Miniland1333** [comment]
Closed by #5
